### PR TITLE
fix: Enum naming convention

### LINKED ISSUE #128: Bug and fix - Requests : SessionTouchScroll
Typo in struct SessionTouchScroll - `CodableKeys` should be `CodingKeys`

### PR DESCRIPTION
**Pull request by Squidonomics**
Closes #128

### CODE REVIEW

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
Could you please add a test case for this @Squidonomics?  It should be something simple as serializing and deserializing the type.

**Comment by Squidonomics** [comment]
> Could you please add a test case for this @Squidonomics? It should be something simple as serializing and deserializing the type.

Yeah no problem, I'll throw one in real quick

File: Tests/UnitTests/APIToRequestMappingTests.swift [hunk 1]
```diff
@@ -191,4 +191,12 @@ class APIToRequestMappingTests: XCTestCase {
...
         XCTAssert(try session.size(window: "myWindow") == (width: 500, height: 500))
     }
+
+    func testSessionTouchScroll() throws {
+        let mockWebDriver: MockWebDriver = MockWebDriver()
+        let session = Session(webDriver: mockWebDriver, existingId: "mySession")
+        let element = Element(session: session, id: "myElement")
+        mockWebDriver.expect(path: "session/mySession/touch/scroll", method: .post)
+        try session.touchScroll(element: element, xOffset: 9, yOffset: 16)
+    }
```
Comment (compnerd) [inline Tests/UnitTests/APIToRequestMappingTests.swift:201]: This definitely is good to keep, but I was thinking that we could just do a round-trip serialising and deserialising the type.  Perhaps a follow up can add those to ensure that we have a simple way to ensure that we have all the fields serialised and deserialised.

**Review by compnerd — APPROVED** [review]

File: Tests/UnitTests/APIToRequestMappingTests.swift (hunk 1 above)
Comment (tristanlabelle) [reply Tests/UnitTests/APIToRequestMappingTests.swift:201]: We already support asserting on the serialized data in a closure, see the example of `testSessionFindElement`. Adding this would be nice.

**Review by tristanlabelle — APPROVED** [review]
Looks good. Thanks!

**Comment by Squidonomics** [comment]
Is this good to be merged in? @tristanlabelle
